# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'transp_ciphers.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(661, 359)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_3.setFont(font)
        self.label_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 0, 1, 1, 1)
        self.mes_Browser = QtWidgets.QTextBrowser(self.frame)
        self.mes_Browser.setReadOnly(False)
        self.mes_Browser.setObjectName("mes_Browser")
        self.gridLayout_3.addWidget(self.mes_Browser, 1, 0, 1, 1)
        self.key_Browser = QtWidgets.QTextBrowser(self.frame)
        self.key_Browser.setReadOnly(False)
        self.key_Browser.setObjectName("key_Browser")
        self.gridLayout_3.addWidget(self.key_Browser, 1, 1, 1, 1)
        self.verticalLayout.addWidget(self.frame)
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout.setObjectName("gridLayout")
        self.Vigenere_radioButton = QtWidgets.QRadioButton(self.frame_3)
        self.Vigenere_radioButton.setChecked(True)
        self.Vigenere_radioButton.setObjectName("Vigenere_radioButton")
        self.gridLayout.addWidget(self.Vigenere_radioButton, 0, 0, 1, 1)
        self.RailF_radioButton = QtWidgets.QRadioButton(self.frame_3)
        self.RailF_radioButton.setObjectName("RailF_radioButton")
        self.gridLayout.addWidget(self.RailF_radioButton, 0, 2, 1, 1)
        self.VertT_radioButton = QtWidgets.QRadioButton(self.frame_3)
        self.VertT_radioButton.setObjectName("VertT_radioButton")
        self.gridLayout.addWidget(self.VertT_radioButton, 0, 3, 1, 1)
        self.Scytale_radioButton = QtWidgets.QRadioButton(self.frame_3)
        self.Scytale_radioButton.setObjectName("Scytale_radioButton")
        self.gridLayout.addWidget(self.Scytale_radioButton, 0, 1, 1, 1)
        self.DoubleT_radioButton = QtWidgets.QRadioButton(self.frame_3)
        self.DoubleT_radioButton.setObjectName("DoubleT_radioButton")
        self.gridLayout.addWidget(self.DoubleT_radioButton, 0, 4, 1, 1)
        self.verticalLayout.addWidget(self.frame_3)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_2.setFont(font)
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_4.setFont(font)
        self.label_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_4.addWidget(self.label_4, 0, 1, 1, 1)
        self.encmes_Browser = QtWidgets.QTextBrowser(self.frame_2)
        self.encmes_Browser.setReadOnly(False)
        self.encmes_Browser.setObjectName("encmes_Browser")
        self.gridLayout_4.addWidget(self.encmes_Browser, 1, 0, 1, 1)
        self.res_Browser = QtWidgets.QTextBrowser(self.frame_2)
        self.res_Browser.setObjectName("res_Browser")
        self.gridLayout_4.addWidget(self.res_Browser, 1, 1, 1, 1)
        self.encrypt_Button = QtWidgets.QPushButton(self.frame_2)
        self.encrypt_Button.setObjectName("encrypt_Button")
        self.gridLayout_4.addWidget(self.encrypt_Button, 2, 0, 1, 1)
        self.decrypt_Button = QtWidgets.QPushButton(self.frame_2)
        self.decrypt_Button.setObjectName("decrypt_Button")
        self.gridLayout_4.addWidget(self.decrypt_Button, 2, 1, 1, 1)
        self.verticalLayout.addWidget(self.frame_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 661, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Transposition ciphers"))
        self.label.setText(_translate("MainWindow", "Type message to encrypt :"))
        self.label_3.setText(_translate("MainWindow", "Type encryption key :"))
        self.Vigenere_radioButton.setText(_translate("MainWindow", "Vigenere cipher"))
        self.RailF_radioButton.setText(_translate("MainWindow", "Rail Fence cipher"))
        self.VertT_radioButton.setText(_translate("MainWindow", "Vertical transposition cipher"))
        self.Scytale_radioButton.setText(_translate("MainWindow", "Scytale cipher"))
        self.DoubleT_radioButton.setText(_translate("MainWindow", "Double transposition cipher"))
        self.label_2.setText(_translate("MainWindow", "Type message to decrypt :"))
        self.label_4.setText(_translate("MainWindow", "Result :"))
        self.encrypt_Button.setText(_translate("MainWindow", "Encrypt"))
        self.decrypt_Button.setText(_translate("MainWindow", "Decrypt"))

